### ISSUE TITLE
"Unique constraint failed" while updating db

### ISSUE THREAD

**Issue by Stefan-Code** [Stefan-Code/gglsbl3#3]
```
INFO: raw data length: 6782 - protocol.py:265
INFO: Deleting "add" chunks ['188931-188949'] - storage.py:223
INFO: Deleting "sub" chunks ['180475-180476,180478-180490'] - storage.py:233
Failed to synchronize with GSB service: UNIQUE constraint failed: hash_prefix.value, hash_prefix.chunk_number, hash_prefix.list_name, hash_prefix.chunk_type
Traceback (most recent call last):
  File "/tmp/virtalenv/bin/gglsbl_client.py", line 67, in run_sync
    sbl.update_hash_prefix_cache()
  File "/tmp/virtalenv/lib/python3.4/site-packages/gglsbl3/client.py", line 44, in update_hash_prefix_cache
    self.storage.store_chunk(chunk)
  File "/tmp/virtalenv/lib/python3.4/site-packages/gglsbl3/storage.py", line 132, in store_chunk
    self.insert_hash_prefix(hash_prefix)
  File "/tmp/virtalenv/lib/python3.4/site-packages/gglsbl3/storage.py", line 147, in insert_hash_prefix
    self.dbc.execute(q, params)
sqlite3.IntegrityError: UNIQUE constraint failed: hash_prefix.value, hash_prefix.chunk_number, hash_prefix.list_name, hash_prefix.chunk_type
```

**Comment by Stefan-Code** [comment]
Seems like this is either caused by a wrong response by the google servers or (maybe more likely) a broken method to report the existing chunks/prefixes in the request process.

**Comment by Stefan-Code** [comment]
TODO: check if afilipovich/gglsbl#10 is relevant
